#basicserver:  port: 9091  servlet:    context-path: /micro#druidspring:  datasource:    username: geweixin    password: 198710
    url: jdbc:mysql://localhost:3306/yoga?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    type:  com.alibaba.druid.pool.DruidDataSource
    name: micro
    initialSize: 6
    asyncInit: true
    maxActive: 64
    minIdle: 6
    maxWait: 60000
    useUnfairLock: true
    poolPreparedStatements: true
    maxOpenPreparedStatements: 100
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: 
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false    application:    name: eureka-client-micro-service    #mybatismybatis:  mapper-locations: classpath:mybatis/*sqlMap.xml  type-aliases-package: micro.bean.po  configuration:     map-underscore-to-camel-case: true     #Croscros:  config:    pathPattern: /**    methods: '*'    origins: '*'    allowedHeaders: '*'    exposedHeaders:      - token      - content-disposition      #eureka    eureka:  client:    serviceUrl:      defaultZone: http://localhost:9090/eureka/  instance:    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}    preferIpAddress: true